---
title: "Template"
author: "Haiyang Jin (hjin317@aucklanduni.ac.nz)"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: 
  pdf_document:
    number_sections: true
    toc: true
version: "1.0"
---

```{r setup and load the related libraries, include=FALSE}
## set chunk options
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(warning = FALSE)
# knitr::opts_chunk$set(fig.width=7, fig.asp =0.618) 
# knitr::opts_chunk$set(comment = "#") # (NA, to remove all hashes)

## load libraries
# libraries for cleaning data
if (!require(dplyr)) {install.packages("dplyr"); library(dplyr)}
if (!require(tidyr)) {install.packages("tidyr"); library(tidyr)}

```


```{r read the data file}
# put the data and this file in the same folder
filename <- "peak.csv"
output.name <- ""

# read data file
behavior.raw <- read.csv(filename)
raw.filename <- basename(filename)
raw.dir <- dirname(filename)

# get the filename of the output
if (output.name == "") {
  output.name <- strsplit(raw.filename, ".csv")
}

# set the filenames for R and SPSS data format
output.acc.R <- paste(raw.dir, "/", output.name, "_acc_R.csv", sep = "")
output.acc.SPSS <- paste(raw.dir, "/", output.name, "_acc_SPSS.csv", sep = "")
output.d.R <- paste(raw.dir, "/", output.name, "_d_R.csv", sep = "")
output.d.SPSS <- paste(raw.dir, "/", output.name, "_d_SPSS.csv", sep = "")
output.rt.R <- paste(raw.dir, "/", output.name, "_rt_R.csv", sep = "")
output.rt.SPSS <- paste(raw.dir, "/", output.name, "_rt_SPSS.csv", sep = "")

```


```{r select certain rows and columns from the data, and calculate the Z value for reaction times}
# behavior.tidyup <- {
#   behavior.raw %>%
#     filter() %>% # select the rows
#     select() %>% # select the columns
#     mutate(scrambleVar = ifelse(scrambleVar == "N", "Normal", ifelse(scrambleVar == "S", "Scrambled", ""))) %>% # rename the levels for scramble variable 
#     group_by() %>% # divide the data based on these conditions
#     mutate(RT.Z = scale()) %>% # calculate the Z value for reaction times within each group
#     mutate(RT.Within3Z = ifelse(RT.Z <= 3 & RT.Z >= -3, 1, ifelse(RT.Z < -3 | RT.Z > 3, 0, NaN))) %>%  # if the Z values are between -3 and 3, will be marked as 1. 
#     ungroup()  # ungroup the data
# }
# 
# behavior.tidyup
```

```{r}
output.SPSS <- {
  behavior.raw %>%
    tbl_df() %>%
    separate(labelLR, c('label', 'x')) %>%
    select(-x, -N170_CentralElec, -N170, - P1_CentralElec) %>%
    spread(label, P1)
}
output.SPSS
write.csv(output.SPSS, file = 'mydata.csv' )
```

