[ALLEEG] = eeglab;

[fn_ICAed, pn_ICAed] = uigetfile(['..' filesep '02_ICAed' filesep '*.set'], 'Please select the ICAed file:');


%% load the data set
EEG = pop_loadset('filename',fn_ICAed,'filepath',pn_ICAed);
eeglab redraw

%% SASICA
% RUN GUI: SASICA from GUI
% EEG = SASICA(EEG,'MARA_enable',0,...
%     'FASTER_enable',1,...
%     'FASTER_blinkchanname','E14 E21',...
%     'ADJUST_enable',1,...
%     'chancorr_enable',1,...
%     'chancorr_channames','No channel',...
%     'chancorr_corthresh','auto 4',...
%     'EOGcorr_enable',1,...
%     'EOGcorr_Heogchannames','E125 E128',...
%     'EOGcorr_corthreshH','auto 4',...
%     'EOGcorr_Veogchannames','E14 E126',...
%     'EOGcorr_corthreshV','auto 4',...
%     'resvar_enable',1,...
%     'resvar_thresh',15,....
%     'SNR_enable',1,...
%     'SNR_snrcut',1,...
%     'SNR_snrBL',[-200 0] ,...
%     'SNR_snrPOI',[0 500] ,...
%     'trialfoc_enable',1,...
%     'trialfoc_focaltrialout','auto',...
%     'focalcomp_enable',1,...
%     'focalcomp_focalICAout','auto',...
%     'autocorr_enable',1,...
%     'autocorr_autocorrint',20,...
%     'autocorr_dropautocorr','auto',...
%     'opts_noplot',0,...
%     'opts_nocompute',0,...
%     'opts_FontSize',14);

rejComp = EEG.reject.gcompreject;

%% remove the marked "bad" components
% RUN GUI: reject components
% EEG = pop_subcomp(EEG, find(rejComp), 0);
fn_rejected = [fn_ICAed(1:4) '_03_Rejected_Individual'];
% [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname',fn_rejected,...
%     'savenew',fn_rejected,'overwrite','on','gui','off'); 

%% save the reject component numbers
EEG.reject.SASICArej = rejComp;
EEG = pop_saveset( EEG, 'filename',fn_rejected,'filepath','.');

%% remove all data
STUDY = []; CURRENTSTUDY = 0; ALLEEG = []; EEG=[]; CURRENTSET=[];
eeglab redraw

